
CREATE TABLE PABELLON
(
    id bigint generated by default as identity primary key,
    nombre varchar(20) not null default '',
    ubicacion varchar(20),
    aforo int,
    disponibilidad boolean,
    photo varchar(100)
);
